name: Setup Node and pnpm

inputs:
  registry-url:
    default: 'https://registry.npmjs.org'
    required: false
    type: string
    description: 'Optional registry to set up for auth. Will set the registry in a project level .npmrc and .yarnrc file, and set up auth to read in from env.NODE_AUTH_TOKEN.'

  scope:
    required: false
    type: string
    description: 'Optional scope for authenticating against scoped registries. Will fall back to the repository owner when using the GitHub Packages registry (https://npm.pkg.github.com/).'

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0

    - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
      with:
        node-version-file: .node-version
        registry-url: ${{ inputs.registry-url }}
        scope: ${{ inputs.scope }}
        package-manager-cache: false
        # see pnpm cache setting below

    - name: Get pnpm store directory
      id: store
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_OUTPUT

    - name: Save and restore pnpm cache on main
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      if: ${{ github.ref_name == 'main' }}
      with:
        path: ${{ steps.store.outputs.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Restore pnpm cache on PR
      uses: actions/cache/restore@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      if: ${{ github.ref_name != 'main' }}
      with:
        path: ${{ steps.store.outputs.STORE_PATH }}
        key: |
          ${{ runner.os }}-pnpm-store-

    - run: pnpm install --frozen-lockfile --ignore-scripts
      shell: bash
